booking/urls.py
from . import views
from django.urls import path

app_name = 'booking'
# URL patterns list for the 'booking' app
urlpatterns = [    
    # Define a URL pattern for the makeAppointment view
    path('', views.makeAppointment.as_view(), name='appointments'),
]

clinic/urls.py
from . import views
from django.urls import path

# URL patterns list for the 'clinic' app
urlpatterns = [
    # Define a URL pattern for the HomePageView view
    path('', views.HomePageView.as_view(), name='home'),    
]

contact/urls.py
from . import views
from django.urls import path


app_name = 'contact'
# URL patterns list for the 'contact' app
urlpatterns = [
    # Define a URL pattern for the ContactUs view
    path('', views.contact, name='contact'),    
]

main/urls.py
from . import views
from django.urls import path

# URL patterns list for the 'main' app
urlpatterns = [
    # Define a URL pattern for the HomePageView view
    path('', views.HomePageView.as_view(), name='home'),    
]

my_clinic/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("booking.urls"), name='booking'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import include, path

# URL patterns list for routing URLs to views
urlpatterns = [
    # Admin site URLs
    path('admin/', admin.site.urls, name = "admin"),

    # Include URLs from the 'clinic' app
    path('', include("clinic.urls"), name = "clinic"),

    # Include URLs from the 'booking' app
    path('booking/', include("booking.urls"), name = "booking"),
    
    # Include URLs from the 'contact' app
    path('contact/', include("contact.urls"), name = "contact"),
    
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User

# Define contand for appointment status

STATUS = (
    (0, "Pending"),
    (1, "Booked"),
    (2, "Canceled"),
)
# Create your models here.

class Doctor(models.Model):
    """
    Model class for storing information about doctors.

    Inherits from Django's models.Model class.
    """

    # Define fields for the model
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=14)
    email = models.EmailField(max_length=100)
    specialization = models.CharField(max_length=100)
    profile_information = models.TextField()

    # Method to represent the object as a string
    def __str__(self):
        return f"Dr {self.firstName} { self.lastName}"

class Administrator(models.Model):
    """
    Model class for storing information about administrators.

    Inherits from Django's models.Model class.
    """
    # Define fields for the model
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

class Therapy(models.Model):
    """
    Model class for storing information about therapies.

    Inherits from Django's models.Model class.
    """
    # Define fields for the model
    name = models.CharField(max_length=100)
    description = models.TextField()
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="therapies")

    # Method to represent the object as a string
    def __str__(self):
        return self.name

class Appointment(models.Model):
    """
    Model class for storing information about appointments.

    Inherits from Django's models.Model class.
    """
    # Define fields for the model
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name ="appointments")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="appointments")
    admin = models.ForeignKey(Administrator, on_delete=models.SET_NULL, null=True, blank=True)
    therapies = models.ManyToManyField(Therapy, related_name="appointments", blank=True)  # ManyToManyField for therapies
    date = models.DateField()
    time = models.TimeField()
    status = models.IntegerField(choices=STATUS, default=0)
    
    # Method to represent the object as a string
    def __str__(self):
        return f"{self.user}'s Appointment"

class Reminder(models.Model):
    """
    Model class for storing reminders.

    Inherits from Django's models.Model class.
    """
    # Define fields for the model
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reminders")
    message = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

clinic/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class HomePage(models.Model):
    """
    Model class for storing information about the home page.

    Inherits from Django's models.Model class.
    """

    # Define fields for the model
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    # Method to represent the object as a string
    def __str__(self):
        return self.title

contact/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Administrator(models.Model):
    """
    Model class for storing information about administrators.

    Inherits from Django's models.Model class.
    """
    # Define fields for the model
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

class Message(models.Model):
    """
    Model class for storing contact information.

    Inherits from Django's models.Model class.
    """
    
    # Define fields for the model
    name = models.CharField(max_length=40)
    phone = models.CharField(null=True, default=0)
    email = models.EmailField(max_length=50)
    subject = models.TextField()
    # Method to represent the object as a string
    def __str__(self):
        return self.name



class UserMessage(models.Model):
    """
    Model class for storing messages sent by users to admin.

    Inherits from Django's models.Model class.
    """
    # Define fields for the model
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sent_messages")
    recipient = models.ForeignKey(Administrator, on_delete=models.CASCADE, related_name="received_messages")
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

booking/views.py
from django.shortcuts import render
from django.views import generic 
from .models import Appointment
# Create your views here.

class makeAppointment(generic.ListView):
    """
    View class for displaying a list of appointments.

    Inherits from Django's generic ListView class.
    """
    # Specify the model to be used for the view
    model = Appointment

    # Specify the template to render
    template_name = "booking.html"
 

clinic/views.py
from django.shortcuts import render
from django.views import generic
from .models import HomePage 

# Create your views here.

class HomePageView(generic.ListView):

    """
    View class for displaying the home page.

    Inherits from Django's generic ListView class.
    """

    # Specify the model to be used for the view
   
    # queryset = HomePage.objects.all()

    model = HomePage

    # Specify the template to render
    template_name = "index.html"

contact/views.py
from django.shortcuts import render, redirect
#from django.views import generic
from django.contrib import messages  # Import the messages module
from .models import Message 
from django.http import HttpResponse

# Create your views here.

def contact(request):
    if request.method == "POST":
        contact = Message()
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        
        # Create and save the message
        Message.objects.create(name=name, phone=phone, email=email, subject=subject)

        # Add a success message
        messages.success(request, 'Thanks for contacting us!')
        # Redirect back to the contact page
        return redirect('contact:contact')

    return render(request, 'contact.html')
"""
class MessageView(generic.ListView):
    
    
    # Specify the model to be used for the view
    model = Message
    # Specify the template to render
    template_name = "contact.html"

"""

booking/templates/booking/book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views Part 1</title>
</head>

<body>
    <h1>Make Appointment </h1>
   
   
</body>

</html>

clinic_app/templates/clinic_app/appointment_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views Part 1</title>
</head>

<body>
    <h1>Make Appointment </h1>
   
   
</body>

</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <!--Meta Tags for Search Engines-->
  <meta charset="UTF-8">
  <meta name="description" content="MED24 Aesthetic Clinic for Beauty surgeries and healthcare">
  <meta name="keywords" content="Aesthetic Clinic, Filler, botox, fit-lifting">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Anass Muhammad Ali">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>MED24 Aesthetic Clinic</title>
</head>
<style>
  {% block style %}{% endblock style %}
</style>

<body>
  <!--Header-->
  <header>

    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">MED24</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'booking:appointments' %}">Appointments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

  </header>

  <!--Main-->
  <main>
    {% block content %}
    <div class="container">

    </div>
    {% endblock content %}




    {% block section %}
    
    {% endblock section %}  

  </main>

  <!--Footer-->
  <footer class="bg-dark text-light py-4">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          &copy; Copyright © reserved for Anass Muhammad Ali
        </div>
      </div>
    </div>
  </footer>
  <script src="{% static 'js/script.js' %}"></script>
  <script src=" {% static 'js/bootstrap.min.js' %}"></script>
  
    <script>
      {% block script %}{% endblock script %}
    </script>

</body>

</html>

templates/booking.html
{% extends 'base.html' %}

{% block content %}
    <h1>Make Appointment </h1>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-lg-center">
        <div class="col-12 col-lg-9">
            <div class="bg-white border rounded shadow-sm overflow-hidden">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    <div class="row gy-4 gy-xl-5 p-4 p-xl-5">
                        <div class="col-12">
                            <label for="name" class="form-label">Full Name <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="col-12 col-md-6">
                            <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <span class="input-group-text">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-envelope" viewBox="0 0 16 16">
                                        <path
                                            d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                                    </svg>
                                </span>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <label for="phone" class="form-label">Phone Number</label>
                            <div class="input-group">
                                <span class="input-group-text">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-telephone" viewBox="0 0 16 16">
                                        <path
                                            d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                                    </svg>
                                </span>
                                <input type="tel" class="form-control" id="phone" name="phone">
                            </div>
                        </div>
                        <div class="col-12">
                            <label for="message" class="form-label">Message <span class="text-danger">*</span></label>
                            <textarea class="form-control" id="message" name="subject" rows="3" required></textarea>
                        </div>
                        <div class="col-12">
                            <div class="d-grid">
                                <button class="btn btn-primary btn-lg" type="submit">Submit</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>this is the homepage</h1>

</div>
{% endblock content %}

templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
</head>
<body>
    <h1>This is the home page</h1>
    
</body>
</html>